######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 4 15:48:24 2010
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../shared/util.h
SOURCES += tst_qabstractitemview.cpp
