######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 18 13:31:52 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += declarative

# Input
HEADERS += eventhandler.h gridview.h
SOURCES += eventhandler.cpp gridview.cpp main.cpp

RESOURCES += gridview.qrc

